-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Vært: 127.0.0.1:3306
-- Genereringstid: 06. 10 2023 kl. 21:49:21
-- Serverversion: 8.0.31
-- PHP-version: 8.0.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `books`
--

-- --------------------------------------------------------

--
-- Struktur-dump for tabellen `produkter`
--

DROP TABLE IF EXISTS `produkter`;
CREATE TABLE IF NOT EXISTS `produkter` (
  `prodId` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `prodTitle` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_danish_ci NOT NULL,
  `prodDescription` text COLLATE utf8mb3_danish_ci,
  `prodPrice` decimal(9,2) NOT NULL,
  `prodDate` date NOT NULL,
  `prodAuthor` varchar(100) COLLATE utf8mb3_danish_ci NOT NULL,
  `prodPages` int UNSIGNED NOT NULL,
  `prodEdition` int NOT NULL,
  `prodLanguage` varchar(50) COLLATE utf8mb3_danish_ci NOT NULL,
  `prodPublisher` varchar(50) COLLATE utf8mb3_danish_ci NOT NULL,
  `prodISBN` int UNSIGNED NOT NULL,
  `prodGenre` varchar(50) COLLATE utf8mb3_danish_ci NOT NULL,
  `prodImage` varchar(100) COLLATE utf8mb3_danish_ci DEFAULT NULL,
  PRIMARY KEY (`prodId`)
) ENGINE=MyISAM AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_danish_ci;

--
-- Data dump for tabellen `produkter`
--

INSERT INTO `produkter` (`prodId`, `prodTitle`, `prodDescription`, `prodPrice`, `prodDate`, `prodAuthor`, `prodPages`, `prodEdition`, `prodLanguage`, `prodPublisher`, `prodISBN`, `prodGenre`, `prodImage`) VALUES
(14, 'Harry Potter og Hemmelighedernes Kammer', '<p>Efter en r&aelig;dsom sommer hos familien Dursley vender Harry tilbage til Hogwarts for at forts&aelig;tte sin troldmandsuddannelse. Men forude venter atter et dramatisk skole&aring;r. Nogle skr&aelig;mmende og uforklarlige angreb finder sted p&aring; skolen, og Harry hvirvles ind i opklaringen af et dystert mysterium om et hemmeligt kammer og et gruopv&aelig;kkende uhyre ...</p>', '249.95', '2015-10-09', 'J.K. Rowling', 400, 6, 'Dansk', 'Gyldendal', 4294967295, 'Fantasy', 'harry-potter-2.jpg'),
(10, 'Dune', '<p>Melange, or \'spice\', is the most valuable - and rarest - element in the universe; a drug that does everything from increasing a person\'s life-span to making intersteller travel possible. And it can only be found on a single planet: the inhospitable desert world Arrakis. Whoever controls Arrakis controls the spice. And whoever controls the spice controls the universe. When the Emperor transfers stewardship of Arrakis from the noble House Harkonnen to House Atreides, the Harkonnens fight back, murdering Duke Leto Atreides. Paul, his son, and Lady Jessica, his concubine, flee into the desert. On the point of death, they are rescued by a band for Fremen, the native people of Arrakis, who control Arrakis\' second great resource: the giant worms that burrow beneath the burning desert sands. In order to avenge his father and retake Arrakis from the Harkonnens, Paul must earn the trust of the Fremen and lead a tiny army against the innumerable forces aligned against them. And his journey will change the universe.</p>', '129.95', '2015-07-16', 'Frank Herbert', 576, 0, 'Engelsk', 'Hodder Paperback', 4294967295, 'Science fiction', 'DUNE.jfif'),
(11, 'En af os lyver', '<p>En helt almindelig mandag eftermiddag m&oslash;des fem studerende p&aring; Bayview High til eftersidning: Brownyn, str&aelig;beren, som er p&aring; vej mod Yale og altid f&oslash;lger reglerne. Addy, sk&oslash;nheden, som har lagt sit liv i h&aelig;nderne p&aring; sin k&aelig;reste. Nate, forbryderen, som er skolens lokale pusher. Cooper, stjernen, som er alle pigers dr&oslash;m og skolens baseball-stjerne. Og Simon, outsideren, som er manden bag skolens berygtede gossip-app. ... men Simon kommer ikke ud af lokalet i live den mandag. Og tirsdag havde han planlagt at poste noget saftig sladder p&aring; sin app om de fire andre. Er &eacute;n af de fire skyldige i Simons mord? Eller er morderen en helt anden?</p>', '99.95', '2020-01-21', 'Karen M. McManus', 400, 2, 'Dansk', 'CarlsenPuls', 4294967295, 'mysterier', 'en-af-os-lyver.jpg'),
(12, 'En af os dræber', '<p>Forts&aelig;ttelsen til En af os lyver \"Kom nu, Bayview, I ved, I har savnet det.&rdquo; Det er et &aring;r siden, Simon d&oslash;de, og et &aring;r siden, at Bayview-firkl&oslash;veret blev renset for alle anklager, og i tiden der er g&aring;et, har der ikke manglet nye sladderaps p&aring; Bayview High. Men ingen har kendt folks hemmeligheder lige s&aring; godt som Simon. Indtil nu. Denne gang er det ikke en app. Det er en leg. Sandhed eller konsekvens. Phoebe er det f&oslash;rste offer. Hvis du v&aelig;lger ikke at lege med, afsl&oslash;rer gamemasteren en hemmelighed. Og Phoebes er m&oslash;rk. Maeve er den n&aelig;ste, og hun burde vide bedre: V&aelig;lg altid \'konsekvens\'. Da det bliver Knox\' tur, er konsekvenserne blevet d&oslash;delige. Simon er v&aelig;k, men nogen er fast besluttet p&aring; at f&oslash;re hans arv videre. Og denne gang er der et helt nye spilleregler.</p>', '99.95', '2021-05-18', 'Karen M. McManus', 384, 2, 'Dansk', 'CarlsenPuls', 4294967295, 'mysterier', 'en-af-os-draeber.jfif'),
(13, 'Harry Potter og De Vises Sten', '<p>Da Harry er 11 &aring;r, f&aring;r han at vide, at hans far var en ber&oslash;mt og respekteret troldmand, og hans mor en overordentlig dygtig heks. Harry er ogs&aring; selv troldmand og skal starte p&aring; Hogwarts skole for heksekunster og troldmandsskab. Han skal bl.a. medbringe tryllestav, troldmandshat og enten en kat, en ugle eller en tudse - og s&aring; starter et eventyrligt liv for Harry, der skal l&aelig;re et hav af magiske tricks og desuden m&aring; tage kampen op mod den onde troldmand, der dr&aelig;bte hans for&aelig;ldre.</p>', '249.95', '2015-10-09', 'J.K. Rowling', 360, 6, 'Dansk', 'Gyldendal', 4294967295, 'Fantasy', 'harry-potter-1.jfif'),
(15, 'Harry Potter og fangen fra Azkaban', '<p>En farlig fange fra troldmandsf&aelig;ngslet Azkaban er undveget, og faren er s&aring; alvorlig, at Ministeriet for Magi ser sig n&oslash;dsaget til at sende efterretninger til den ikke-magiske verden. Harry er specielt i fare, da fangen &aring;benbart er ude efter ham.</p>', '249.95', '2015-10-09', 'J.K. Rowling', 484, 6, 'Dansk', 'Gyldendal', 4294967295, 'Fantasy', 'harry-potter-3.jfif'),
(16, 'Harry Potter og Flammernes Pokal', '<p>En storsl&aring;et intermagisk begivenhed vil finde sted p&aring; Hogwarts i &aring;r. Harry Potter stilles over for de hidtil mest kr&aelig;vende udfordringer i sin troldmandskarriere; men M&oslash;rkets repr&aelig;sentanter lurer i hver en krog, og alt tyder p&aring;, at udfordringerne denne gang er mere, end Harry kan magte.</p>', '249.95', '2015-10-09', 'J.K. Rowling', 616, 6, 'Dansk', 'Gyldendal', 4294967295, 'Fantasy', 'harry-potter-4.jfif'),
(17, 'Harry Potter og Fønixordenen', '<p>Harry Potter er desperat efter at komme tilbage til Hogwarts og finde ud af, hvorfor Ron og Hermione har v&aelig;ret s&aring; hemmelighedsfulde hele sommeren. Men det femte &aring;r p&aring; Hogwarts bliver hverken let eller behageligt for Harry. Ministeriet for Magi n&aelig;gter at tro p&aring; Harrys og Dumbledores forsikringer om, at Voldemort er vendt tilbage. Ministeren sender en repr&aelig;sentant til skolen, som skal s&oslash;rge for at udbrede Ministeriets holdning og lukke munden p&aring; Harry - med alle midler. Og med katastrofale f&oslash;lger ...</p>', '249.95', '2015-10-09', 'J.K. Rowling', 848, 5, 'Dansk', 'Gyldendal', 4294967295, 'Fantasy', 'harry-potter-5.jfif'),
(18, 'Harry Potter og Halvblodsprinsen', '<p>Harry har tilbragt de f&oslash;rste uger af sommerferien hos familien Dursley med at ligge p&aring; sin seng og stirre op i loftet. Han s&oslash;rger over sin dr&aelig;bte gudfar Sirius, mens han genoplever det grufulde opg&oslash;r med D&oslash;dsgardisterne i Ministeriet for Magi og den sindsoprivende duel mellem Dumbledore og Lord Voldemort. Nu sidder han ved vinduet og venter p&aring; Dumbledore, der har meldt sin ankomst pr. uglepost. Langt om l&aelig;nge vil Dumbledore give svar p&aring; Harrys mange sp&oslash;rgsm&aring;l om sammenh&aelig;ngen mellem ham selv og Lord Voldemort. Harry gl&aelig;der sig til at slippe v&aelig;k fra Ligusterv&aelig;nget. M&aring;ske fordi han ikke ved, hvad der venter ham.</p>', '249.95', '2015-10-09', 'J.K. Rowling', 560, 5, 'Dansk', 'Gyldendal', 4294967295, 'Fantasy', 'harry-potter-6.jfif'),
(19, 'Harry Potter og Dødsregalierne', '<p>Harry er blevet p&aring;lagt en dyster, farlig og tilsyneladende umulig opgave: Han skal finde og &oslash;del&aelig;gge Voldemorts tilbagev&aelig;rende Horcruxer. Sammen med Ron og Hermione begiver han sig ud p&aring; den h&aring;bl&oslash;se jagt. Ingen af de tre har nogen anelse om, hvor de skal lede. Og de har ikke meget tid, for Voldemort leder ogs&aring; - efter Harry.</p>', '249.95', '2015-10-09', 'J.K. Rowling', 656, 5, 'Dansk', 'Gyldendal', 4294967295, 'Fantasy', 'harry-potter-7.jfif'),
(20, 'Percy Jackson and the Lightning Thief', '<p>Half boy. Half God. All Hero! I was just a normal kid, I went to school (got expelled a lot, but that wasn\'t my fault), played sports and hung out with my best friend. Until I accidentally vaporized my maths teacher. Now, I spend my time at Camp Half Blood, battling monsters and generally trying to stay alive. And now that Zeus thinks I\'ve stolen his lightning bolt, staying alive is going to be even harder...</p>', '119.95', '2013-07-04', 'Rick Riordan', 400, 0, 'Engelsk', 'Puffin Books', 4294967295, 'Fantasy', 'percy-jackson-1.jfif'),
(21, 'Percy Jackson and the Sea of Monsters', '<p>Half boy. Half God. All Hero! - I look like a normal kid. Only there\'s a difference. Poseidon, God of the Sea is my dad. Which sounds cool, but actually means there is usually someone (or something), somewhere, trying to kill me. Now I live at Camp Half-Blood, with other kids like me. But Camp Half-Blood is a bit different to most summer camps. Instead of toasting marshmallows and singing campfire songs, we battle giant cannibals at dodgeball. This time, we\'re under attack, and I need to get my hands on the Golden Fleece or we\'ll be invaded by monsters. Big ones.</p>', '119.95', '2013-07-04', 'Rick Riordan', 304, 0, 'Engelsk', 'Puffin Books', 4294967295, 'Fantasy', 'percy-jackson-2.jfif'),
(22, 'Percy Jackson and the Titan\'s Curse', '<p>Half boy. Half God. ALL Hero. My life could have been the same as an ordinary teenager. Except my dad is Poseidon, and I live in a camp full of half Gods and mythical creatures. So instead, my days are spent combatting half-lion half-humans and trying to live a somewhat normal life. But normalcy has just gone out the window. My friend Annabeth is missing, a Goddess is in chains, and only five of us can join the quest to save the day. Oh and guess what. The Oracle has predicted that not all of us will survive...</p>', '119.95', '2013-07-04', 'Rick Riordan', 320, 0, 'Engelsk', 'Puffin Books', 4294967295, 'Fantasy', 'percy-jackson-3.jfif'),
(23, 'Percy Jackson and the Battle of the Labyrinth', '<p>Half boy. Half God. ALL Hero. Being the son of a Greek God, nothing in my life has been straightforward. Or monster-free. And it looks like that\'s not going to change anytime soon now that my arch enemy Luke wants to invade Camp Half-Blood via an ancient labyrinth. If he succeeds, thousands of bloodthirsty monsters will attack. So it\'s goodbye sunshine, hello darkness as four of us descend into the terrifying underground and beyond ...</p>', '119.95', '2013-07-04', 'Rick Riordan', 384, 0, 'Engelsk', 'Puffin Books', 4294967295, 'Fantasy', 'percy-jackson-4.jfif'),
(24, 'Percy Jackson and the Last Olympian', '<p>Half boy. Half God. ALL Hero. Normally when you turn sixteen you get a really cool present. But, being sixteen and the son of Poseidon can never be that simple. So instead, I get a prophecy that says the fate of the entire world rests on my shoulders. Great. On top of that, Kronos, Lord of the Titans, is attacking New York City and the dreaded monster Typhon is heading our way. So, it\'s me and forty of my demi-god friends versus untold evil. Happy birthday to me!</p>', '119.95', '2013-07-04', 'Rick Riordan', 416, 0, 'Engelsk', 'Puffin Books', 4294967295, 'Fantasy', 'percy-jackson-5.jfif'),
(25, 'Percy Jackson and the Chalice of the Gods', '<p>A brand new Percy Jackson adventure! The original hero. A brand-new adventure ... Percy Jackson has saved the world multiple times - battling monsters, Titans, even giants - but these days the modern-day son of Poseidon is hoping for a regular final year at school. Too bad the Greek gods have other plans, and three new quests for Percy to complete. First up: the cupbearer of the gods, Ganymede, is missing his golden chalice. Not only is this embarrassing (why do the gods keep losing their magical items?), it\'s also potentially disastrous. One sip from the cup will turn any mortal into a powerful god. And the old gods do not take kindly to newbies. Can Percy and his friends Annabeth and Grover find the chalice before it falls into the wrong hands? And even if they do, will they be able to resist its awesome power ...? Readers new to the Percy Jackson universe and long-time fans will love this epic adventure - full of legendary heroes, mythical creatures, ancient Greek gods and enduring friendship - from the global bestseller Rick Riordan.</p>', '169.95', '2023-09-26', 'Rick Riordan', 288, 0, 'Engelsk', 'Puffin Books', 4294967295, 'Fantasy', 'percy-jackson-6.jfif'),
(26, 'The Hunger Games', '<p>First in the ground-breaking HUNGER GAMES trilogy. Set in a dark vision of the near future, a terrifying reality TV show is taking place. Twelve boys and twelve girls are forced to appear in a live event called The Hunger Games. There is only one rule: kill or be killed. When sixteen-year-old Katniss Everdeen steps forward to take her younger sister\'s place in the games, she sees it as a death sentence. But Katniss has been close to death before. For her, survival is second nature.</p>', '139.95', '2011-12-01', 'Suzanne Collins', 448, 0, 'Engelsk', 'Scholastic', 4294967295, 'Science fiction', 'the-hunger.games-1.jfif'),
(27, 'Catching Fire', '<p>The terrifying sequel to The Hunger Games! After winning the brutal Hunger Games, Katniss Everdeen returns to her district, hoping for a peaceful future. But Katniss starts to hear rumours of a deadly rebellion against the Capitol. A rebellion that she and Peeta have helped to create. As Katniss and Peeta are forced to visit the districts on the Capitol\'s cruel Victory Tour, the stakes are higher than ever. Unless Katniss and Peeta can convince the world that they are still lost in their love for each other, the consequences will be horrifying.</p>', '129.95', '2011-12-01', 'Suzanne Collins', 448, 0, 'Engelsk', 'Scholastic', 4294967295, 'Science fiction', 'the-hunger-games-2.jfif'),
(28, 'Mockingjay', '<p>Against all odds, Katniss Everdeen has survived the Hunger Games twice. But now that she\'s made it out of the bloody arena alive, she\'s still not safe. The Capitol is angry. The Capitol wants revenge... Welcome to the thrilling final instalment of the ground-breaking trilogy.</p>', '129.95', '2011-12-01', 'Suzanne Collins', 448, 1, 'Engelsk', 'Scholastic', 4294967295, 'Science fiction', 'the-hunger-games-3.jpg'),
(29, 'The Ballad of Songbirds and Snakes', '<p>The Ballad of Songbirds and Snakes revisits the world of Panem sixty-four years before the events of The Hunger Games. - Ambition will fuel him. Competition will drive him. But power has its price. It is the morning of the reaping that will kick off the tenth annual Hunger Games. In the Capitol, eighteen-year-old Coriolanus Snow is preparing for his one shot at glory as a mentor in the Games. The once-mighty house of Snow has fallen on hard times, its fate hanging on the slender chance that Coriolanus will be able to outcharm, outwit, and outmaneuvre his fellow students to mentor the winning tribute. The odds are against him. He\'s been given the humiliating assignment of mentoring the female tribute from District 12, the lowest of the low. Their fates are now completely intertwined; every choice Coriolanus makes could lead to favour or failure, triumph or ruin. Inside the arena, it will be a fight to the death. Outside the arena, Coriolanus starts to feel for his doomed tribute... and must weigh his need to follow the rules against his desire to survive no matter what it takes.</p>', '134.95', '2021-07-08', 'Suzanne Collins', 528, 0, 'Engelsk', 'Scholastic', 4294967295, 'Science fiction', 'the-hunger-games-4.jfif');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
